=== Pergod/GradeManageSystem/src/Student.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Exam (student+) >
<!ELEMENT student (name,sex,grade)>
	<!ATTLIST student
		id CDATA #REQUIRED
	>
<!ELEMENT name (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT sex (#PCDATA)>

=== Pergod/GradeManageSystem/src/Student.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Exam SYSTEM "D:\workspace\GradeManageSys\src\Student.dtd">
<Exam>
	<student id="1">
		<name>小明</name>
		<sex>男</sex>
		<grade>20</grade>
	</student>
	
	<student id="3">
		<name>小明</name>
		<sex>女</sex>
		<grade>87.0</grade>
	</student>
</Exam>
